feat: audit log table and bpmn coloring
ducanhpham0312/zeevision pull request #289
Opened 2023-12-06 14:27 UTC by ducanhpham0312

### Linked issue

Closes ducanhpham0312/zeevision-private#150

### Description

- Audit Log table to SingleInstancePage
- Add coloring to BPMN diagram depends on the audit log state
- Fix a bug where resizing a window including bpmn diagram breaks the application
- Update sample query to only include necessary auditlog queries.
- "Incompatible" incident queries are also modified.

### Testing

- Run test bench, start the application and run the query in pgAdmin.
- Open `/instances/11` and verify that some elements in the BPMN diagram are colored (green border, red-filled, green-filled). 
  - Green border: The element has completed or have been resolved from an incident
  - Green-filled: The element is in the activating - completing phase (requires user focus)
  - Red-filled: There is an incident occur in the element (requires user focus)
  - Gray-filled: The element is terminated.
  - The arrow is always green (I cannot color the triangle though :/ ).
  - Please also comment and make suggestion on color and opacity selection etc.
- To test the color change when an incident occurs:
  - Deploy the money-loan process
  - Create an instance without any variable. The gateway in the bpmn should be red (where incident occurs)
  - Open ZSM with that instance and set the variable (e.g., debt : 100). Then switch to the incident tab and hit resolve. The gateway should now have green border color.
- The `Audit Log` table are visible after choosing the corresponding tab.
- Open SingleProcessPage or SingleInstancePage and try resizing the browser window. It should not break the app.

2023-12-07 12:26 UTC, kauppie requested changes
Code seems alright except that I don't get the BPMN coloring:
![image](https://github.com/ducanhpham0312/zeevision/assets/11910622/86110109-d172-4058-9508-fceebf922d39)

2023-12-08 01:06 UTC, kauppie requested changes
Seems alright, but coloring doesn't work as I expected. Here is an example of how ZSM and zeevision differ:

![image](https://github.com/ducanhpham0312/zeevision/assets/11910622/6740b182-e9eb-4dad-b8ba-dd5ba11dfbb8)

I expected the path to be colored through completing the instance, but it stops at the first gateway. Does this require audit log feature to be working?

I also `Throw Error` on certain task and the coloring didn't work, although the table shows the incident:

![image](https://github.com/ducanhpham0312/zeevision/assets/11910622/7640045d-03c9-4999-ad23-c3fcc07d2125)

2023-12-09 00:11 UTC, ducanhpham0312 commented on frontend/src/pages/SingleInstancePage.tsx
> +        incident.state === "CREATED" ? "INCIDENT_CREATED" : "INCIDENT_RESOLVED";
How did you perform the "Fail the job" step though? I initially thought incident only has 2 states `CREATED` and `RESOLVED`... what is the incident state when you fail the job? And how about reversing the ternary operator:
```suggestion
        incident.state === "RESOLVED" ? "INCIDENT_RESOLVED" : "INCIDENT_CREATED";
```

2023-12-09 00:21 UTC, ducanhpham0312 commented
And to answer your PR comment, yes, everything requires the audit log store API so it's not visible when you start an instance. If you create an instance that caused an incident in the progress, then you may see the coloring.

2023-12-09 00:24 UTC, ducanhpham0312 commented on frontend/src/pages/SingleInstancePage.tsx
> +        incident.state === "CREATED" ? "INCIDENT_CREATED" : "INCIDENT_RESOLVED";
I tested myself and the task turns red :D 
![Screenshot 2023-12-09 at 2 24 22](https://github.com/ducanhpham0312/zeevision/assets/77518288/2ec578ee-f92e-4809-8d4e-c6fc51cc5aa5)

2023-12-09 01:12 UTC, kauppie commented on frontend/src/pages/SingleInstancePage.tsx
> +        incident.state === "CREATED" ? "INCIDENT_CREATED" : "INCIDENT_RESOLVED";
I retried and now it works, somehow. Can you confirm that the incident table doesn't show correct information in the `Element ID`  field as it differs from ZSM?

2023-12-09 09:49 UTC, ducanhpham0312 commented
The latest commit fixed the table pagination when selecting "All". It was fixed in a previous PR, but somehow got reverted :/

2023-12-09 14:35 UTC, kauppie commented on frontend/src/components/BpmnViewer/BpmnViewer.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
This wasn't fixed.

2023-12-09 14:38 UTC, kauppie approved these changes

2023-12-09 15:29 UTC, merged